name: C++ CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y cmake g++ 
    - name: Build
      run: |
        cmake -B build -S .
        cd build
        make
    - name: Run tests
      run: |
        cd build
        make test
