name: C++ Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: gcc
        update-environment: true

    - name: Install dependencies
      run: sudo apt-get install -y cmake make g++

    - name: Build the code
      run: |
        cmake -B build -S .
        cd build
        make

    - name: Run the application
      run: ./build/src/assignment_cli

    - name: Run tests
      run: |
        cd build
        make test || ./test/assignment_test
